name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          echo "npm install ..."
          npm install
          
      - name: Run test
        run: |
          echo "npm run test ..."
          npm run test 
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Deploy on Heroku action
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_MAIL}}
